[tool.ruff]
preview = true
line-length = 150

[tool.ruff.lint]
# FIXME
extend-ignore = [
  "F403",
  "F405", # may be undefined, or defined from star imports
]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"

[tool.ruff.lint.isort]
combine-as-imports = true

[dependency-groups]
dev = [
    "ruff>=0.14.1",
]
