name: 'Setup Spack'
inputs:
  cache-dir:
    description: 'Directory for spack cache'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install apt-get packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      # - llvm are required for h2yaml, an we cannot build llvm on the CI
      # - libnuma is required, because SPACK fail to build it
      with:
        packages: libnuma-dev libllvm18 llvm-18 llvm-18-dev libclang-18-dev
    - name: Checkout Spack
      uses: actions/checkout@v4
      with:
        repository: spack/spack
        ref: releases/latest
        path: external/spack
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        detached: true
      if: ${{ github.event_name == 'workflow_dispatch' && (inputs.debug_enabled == true || inputs.debug_enabled == 'true') }}
    - name: Setup spack environment
      shell: bash
      run: |
        . external/spack/share/spack/setup-env.sh
        spack repo add ./
        spack compiler find
        # find external packages known to spack (avoid bzip2 and xz since
        # they cause build failures in elfutils).
        spack external find --all --exclude bzip2 --exclude xz
        # Setup a spack mirror to store built packages. More info can be
        # found here:
        # https://spack.readthedocs.io/en/latest/binary_caches.html
        spack mirror add --autopush --unsigned thapi_cache ${{ inputs.cache-dir }}
    - name: Fix Spack Package for yaml
      shell: bash
      run: |
        # spack v1.0 stores both compilers and external packages in the
        # same packages.yaml (compared to packages.yaml and compilers.yaml
        # pre v1.0). So, even if we pass `--exclude llvm` to
        # `spack external find`, packages.yaml will have an entry for llvm
        # as `spack compiler find` finds it. Therefore, instead of adding
        # a new llvm entry in packages.yaml, we have to change the
        # existing one.
        #
        # find the prefix where libclang is installed
        llvm_prefix=$(llvm-config-18 --prefix)
        # point spack to llvm+clang installed through apt-get
        cp ~/.spack/packages.yaml ~/.spack/packages.yaml.old
        # Assume `spec` key come before `prefix` key in yaml
        #  - spec: intel-oneapi-compilers@2025.2.0`
        #    prefix: /opt/aurora/25.190.0/oneapi 
        awk -v pkg="llvm@18" -v new_prefix=${llvm_prefix} '
            match($0, "- spec: "pkg) {f=1} # Match spec context
            f && /prefix:/ {sub($2, new_prefix); f=0} # Use new prefix if in correct spec
            {print}
        ' ~/.spack/packages.yaml.old > ~/.spack/packages.yaml
