name: 'Setup Spack'
inputs:
  cache-dir:
    description: 'Directory for spack cache'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install apt-get packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      # - llvm are required for h2yaml, an we cannot build llvm on the CI
      with:
        packages: libllvm18 llvm-18 llvm-18-dev libclang-18-dev
    - name: Checkout Spack
      uses: actions/checkout@v4
      with:
        repository: spack/spack
        ref: releases/latest
        path: external/spack
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        detached: true
      if: ${{ github.event_name == 'workflow_dispatch' && (inputs.debug_enabled == true || inputs.debug_enabled == 'true') }}
    - name: Setup spack environment
      shell: bash
      run: |
        . external/spack/share/spack/setup-env.sh
        spack repo add ./
        spack compiler find
        # Setup a spack mirror to store built packages. More info can be
        # found here:
        # https://spack.readthedocs.io/en/latest/binary_caches.html
        spack mirror add --autopush --unsigned thapi_cache ${{ inputs.cache-dir }}
