variables:
  PROJ: "Performance"
  QUEUE: "capacity"
  TIME: "3:00:00"
  ANL_AURORA_SCHEDULER_PARAMETERS: "-q ${QUEUE} -l select=1,walltime=${TIME},filesystems=home -A ${PROJ}"
  AURORA_WORKDIR: "/lus/flare/projects/${PROJ}/thapi/"
  AURORA_SPEC: "thapi@develop+sync-daemon-mpi+archive"
  AURORA_OPTS: "--concurrent-packages 2 -j32 --show-log-on-error --fail-fast"
  AURORA_TOOLS: "bats ittapi py-ittapi"
  ANL_POLARIS_SCHEDULER_PARAMETERS: "-q ${QUEUE} -l select=1,walltime=${TIME},filesystems=home -A ${PROJ}"
  POLARIS_WORKDIR: "/lus/grand/projects/${PROJ}/thapi/"
  POLARIS_SPEC: "thapi@develop+archive"
  POLARIS_OPTS: "--concurrent-packages 2 -j16 --show-log-on-error --fail-fast"
  POLARIS_TOOLS: "bats ittapi py-ittapi clinfo"
stages:
    - test
.common-steps:
  # Create ci directory
  - &create-ci-dir |
    run_dir=$(mktemp -d --tmpdir=${WORKDIR} ${CI_COMMIT_SHA}_XXXXXXXXXX)
    echo "THAPI_RUN_DIR=${run_dir}"
    cd ${run_dir}
  # Clone and isolate spack for CI (see below link):
  # https://spack.readthedocs.io/en/latest/configuration.html#overriding-local-configuration
  - &clone-spack |
    git clone -c feature.manyFiles=true -b releases/latest https://github.com/spack/spack.git
    export SPACK_DISABLE_LOCAL_CONFIG=true
    export SPACK_USER_CACHE_PATH=/tmp/spack-${CI_COMMIT_SHA}
    . spack/share/spack/setup-env.sh
  # Find compilers and external packages known to spack (avoid bzip2 and xz since
  # they cause build failures in elfutils).
  - &spack-find |
    spack compiler find
    spack external find --all --exclude bzip2 --exclude xz
  # Add THAPI-spack as a repo
  - &add-thapi-spack-repo |
    git clone https://github.com/argonne-lcf/THAPI-spack.git
    cd ./THAPI-spack
    git checkout ${CI_COMMIT_SHA}
    spack repo add .
    cd ..
  # Install and load thapi
  - &install-and-load-thapi |
    spack install ${OPTS} ${SPEC}
    spack load ${SPEC}
    # Install and load test tools
  - &install-and-load-test-tools |
    spack install ${OPTS} ${TOOLS}
    spack load ${TOOLS}
  # Run tests
  - &run-tests |
    git clone --depth 1 https://github.com/argonne-lcf/THAPI.git -b devel
    cd ./THAPI
    bats ./integration_tests/
aurora:
  stage: test
  extends: .aurora-batch-runner
  script:
    # Set variables nedded by the workflow: WORKDIR, SPEC and OPT
    - |
      export WORKDIR=${AURORA_WORKDIR} SPEC=${AURORA_SPEC} OPTS=${AURORA_OPTS} \
        TOOLS=${AURORA_TOOLS}
    # Load available modules so spack finds those packages
    - |
      module load oneapi
    - *create-ci-dir
    - *clone-spack
    - *spack-find
    - *add-thapi-spack-repo
    - *install-and-load-thapi
    - *install-and-load-test-tools
    - *run-tests
polaris:
  stage: test
  extends: .polaris-batch-runner
  script:
    # Set variables nedded by the workflow: WORKDIR, SPEC and OPT
    - |
      export WORKDIR=${POLARIS_WORKDIR} SPEC=${POLARIS_SPEC} OPTS=${POLARIS_OPTS} \
        TOOLS=${AURORA_TOOLS}
    # Load available modules so spack finds those packages
    - |
      module use /soft/modulefiles
      module load PrgEnv-gnu
      module load spack-pe-base cmake protobuf python
    - *create-ci-dir
    - *clone-spack
    - *spack-find
    - *add-thapi-spack-repo
    - *install-and-load-thapi
