variables:
  PROJ: "Performance"
  QUEUE: "prod"
  TIME: "1:30:00"
  WRK_DIR: "/lus/flare/projects/${PROJ}/thapi/"
  ANL_AURORA_SCHEDULER_PARAMETERS: "-q ${QUEUE} -l select=1,walltime=${TIME},filesystems=home -A ${PROJ}"
  SPEC: "thapi@develop+mpi+sync-daemon-mpi+archive+test-dependencies"
  OPTS: "--concurrent-packages 2 -j32 --show-log-on-error --fail-fast"

stages:
    - .pre
    - build
    - test

setup:
  stage: .pre
  extends: .aurora-shell-runner
  script:
    # create ci directory
    - |
      cd ${WRK_DIR}
      suffix=$(( $(find . -maxdepth 1 -type d -name "${CI_COMMIT_SHA}*" | wc -l) + 1 ))
      mkdir -p ${CI_COMMIT_SHA}_${suffix}
      cd ${CI_COMMIT_SHA}_${suffix}
      # setup spack
    - git clone -c feature.manyFiles=true -b releases/latest https://github.com/spack/spack.git
    - . spack/share/spack/setup-env.sh
      # Isolate spack for CI (see below link):
      # https://spack.readthedocs.io/en/latest/configuration.html#overriding-local-configuration
    - export SPACK_DISABLE_LOCAL_CONFIG=true
    - export SPACK_USER_CACHE_PATH=/tmp/spack-${CI_COMMIT_SHA}
    - module load oneapi
    - spack compiler find
      # find external packages known to spack (avoid bzip2 and xz since they cause
      # build failures in elfutils).
    - spack external find --all --exclude bzip2 --exclude xz
      # setup THAPI-spack
    - git clone https://github.com/argonne-lcf/THAPI-spack.git
    - cd ./THAPI-spack
    - git checkout ${CI_COMMIT_SHA}
    - spack repo add .

install:
  stage: build
  extends: .aurora-batch-runner
  script:
    - |
      cd ${WRK_DIR}/
      suffix=$(( $(find . -maxdepth 1 -type d -name "${CI_COMMIT_SHA}*" | wc -l) ))
      cd ${CI_COMMIT_SHA}_${suffix}
    - export SPACK_DISABLE_LOCAL_CONFIG=true
    - export SPACK_USER_CACHE_PATH=/tmp/spack-${CI_COMMIT_SHA}
    - . spack/share/spack/setup-env.sh
    - spack install ${OPTS} ${SPEC}

integration_tests:
  stage: test
  extends: .aurora-batch-runner
  script:
    - |
      cd ${WRK_DIR}/
      suffix=$(( $(find . -maxdepth 1 -type d -name "${CI_COMMIT_SHA}*" | wc -l) ))
      cd ${CI_COMMIT_SHA}_${suffix}
    - export SPACK_DISABLE_LOCAL_CONFIG=true
    - export SPACK_USER_CACHE_PATH=/tmp/spack-${CI_COMMIT_SHA}
    - . spack/share/spack/setup-env.sh
    - spack load ${SPEC}
    - module load oneapi
    # FIXME: For the time being we delete THAPI if it exists.
    - rm -rf THAPI
    - git clone https://github.com/argonne-lcf/THAPI.git -b devel
    - cd ./THAPI
    - bats ./integration_tests/
