variables:
  SPEC: "thapi@develop+archive+test-dependencies"
  OPTS: "--concurrent-packages 2 -j32 --show-log-on-error --fail-fast"
  PROJ: "Performance"
  QUEUE: "prod"
  TIME: "2:00:00"
  ANL_AURORA_SCHEDULER_PARAMETERS: "-q ${QUEUE} -l select=1,walltime=${TIME},filesystems=home -A ${PROJ}"

# NOTE: uses default stages: .pre build test deploy .post
stages:
    - .pre
    - build
    - test

setup:
  stage: .pre
  extends: .aurora-shell-runner
  script:
    - mkdir -p ~/ci/thapi/${CI_COMMIT_SHA}
    - cd ~/ci/thapi/${CI_COMMIT_SHA}
    - git clone --depth=2 -b releases/latest https://github.com/spack/spack.git
    - export SPACK_DISABLE_LOCAL_CONFIG=1
    - . spack/share/spack/setup-env.sh
    - spack bootstrap root .
    - git clone https://github.com/argonne-lcf/THAPI-spack.git
    - cd ./THAPI-spack
    - git checkout ${CI_COMMIT_SHA}
    - spack repo add .
    - spack compiler find
      # find external packages known to spack (avoid bzip2 and xz since
      # they cause build failures in elfutils).
    - spack external find --all --exclude bzip2 --exclude xz

install:
  stage: build
  extends: .aurora-batch-runner
  script:
    - cd ~/ci/thapi/${CI_COMMIT_SHA}
    - export SPACK_DISABLE_LOCAL_CONFIG=1
    - . spack/share/spack/setup-env.sh
    - spack install ${OPTS} ${SPEC}

integration_tests:
  stage: test
  extends: .aurora-batch-runner
  script:
    - cd ~/ci/thapi/${CI_COMMIT_SHA}
    - export SPACK_DISABLE_LOCAL_CONFIG=1
    - . spack/share/spack/setup-env.sh
    - spack load ${SPEC}
    - git clone https://github.com/argonne-lcf/THAPI.git -b devel
    - cd ./THAPI
    - bats ./integration_tests/
