variables:
  SPACK_OPT: "--concurrent-packages 2 --show-log-on-error --fail-fast"
  CACHE_DIR: "${{ github.workspace }}/thapi_cache_${{ github.run_id }}"
  PROJ: "Performance"

.site-id-token: &site-id-token
  id_tokens:
    CI_JOB_JWT:
      aud: https://gitlab-ci.alcf.anl.gov

.shell:
  <<: *site-id-token
  tags:
    - aurora
    - shell
  before_script:
    - module list

.batch:
  <<: *site-id-token
  tags:
    - aurora
    - batch
  variables:
    ANL_AURORA_SCHEDULER_PARAMETERS: "-q debug -l select=1,walltime=1:00:00,filesystems=home -A $PROJ"

# NOTE: uses default stages: .pre build test deploy .post
stages:
    - .pre
    - build

setup:
  stage: .pre
  extends: .shell
  script:
    - mkdir -p ~/ci/thapi/${CI_COMMIT_SHA}
    - cd ~/ci/thapi/${CI_COMMIT_SHA}
    - git clone --depth=2 -b releases/latest https://github.com/spack/spack.git
    - export SPACK_DISABLE_LOCAL_CONFIG=1
    - . spack/share/spack/setup-env.sh
    - spack bootstrap root .
    - git clone https://github.com/argonne-lcf/THAPI-spack.git
    - cd ./THAPI-spack
    - git checkout ${CI_COMMIT_SHA}
    - spack repo add .
    - spack compiler find
      # find external packages known to spack (avoid bzip2 and xz since
      # they cause build failures in elfutils).
    - spack external find --all --exclude bzip2 --exclude xz

install:
  stage: build
  extends: .batch
  script:
    - cd ~/ci/thapi/${CI_COMMIT_SHA}
    - . spack/share/spack/setup-env.sh
    - spack install $SPACK_OPT thapi@develop+archive+test-dependencies

test:
  stage: test
  extends: .batch
  script:
    - cd ~/ci/thapi/${CI_COMMIT_SHA}
    - . spack/share/spack/setup-env.sh
    - spack load thapi@develop+archive+test-dependencies
    - git clone https://github.com/argonne-lcf/THAPI.git -b devel
    - cd ./THAPI
    - bats ./integration_tests/
