name: 'Setup Thapi Deps'
inputs:
  cache-dir:
    description: 'Directory for spack cache'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        detached: true
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
    - name: Install apt-get packages
      run: |
        # install libnuma-dev
        sudo apt-get install libnuma-dev
    - name: Checkout Spack
      uses: actions/checkout@v4
      with:
        repository: spack/spack
        ref: releases/latest
        path: external/spack
    - name: Setup spack environment
      shell: bash
      run: |
        . external/spack/share/spack/setup-env.sh
        spack repo add ./
        spack compiler find
        # find external packages known to spack (avoid bzip2 and xz since
        # they cause build failures in elfutils).
        spack external find --all --exclude bzip2 --exclude xz

        # Setup a spack mirror to store built packages. More info can be
        # found here:
        # https://spack.readthedocs.io/en/latest/binary_caches.html
        spack mirror add --autopush --unsigned thapi_cache ${{ inputs.cache-dir }}

