name: THAPI unit tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

env:
  SPACK_OPT: "--concurrent-packages 2 --show-log-on-error --fail-fast"
  CACHE_DIR: "${{ github.workspace }}/thapi_cache_${{ github.run_id }}"
  DEPRECATED_CACHE_DIR: "${{ github.workspace }}/thapi_cache_deprecated_${{ github.run_id }}"

jobs:
  install_deprecated_dependencies:
    runs-on: ubuntu-latest
    name: Install dependencies (deprecated)
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ inputs.debug_enabled }}
    - name: Checkout dependencies (spack,...)
      uses: ./.github/actions/setup-thapi-deps
      with:
        cache-dir: ${{ env.DEPRECATED_CACHE_DIR }}
    - name: Install dependencies
      run: |
        . external/spack/share/spack/setup-env.sh
        spack install --only dependencies $SPACK_OPT thapi@0.0.12
    - name: Upload thapi build cache
      uses: actions/upload-artifact@v4
      with:
        name: thapi_cache_deprecated
        include-hidden-files: true
        path: ${{ env.DEPRECATED_CACHE_DIR }}
        if-no-files-found: error
    - name: Block to allow inspecting failures
      run: sleep 120m
      if: ${{ failure() && inputs.debug_enabled }}

  install_deprecated:
    strategy:
      matrix:
        version: ['thapi@0.0.7', 'thapi@0.0.8', 'thapi@0.0.9', 'thapi@0.0.10', 'thapi@0.0.11', 'thapi@0.0.12']
    needs: install_deprecated_dependencies
    runs-on: ubuntu-latest
    name: Install ${{ matrix.version }} (deprecated)
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ inputs.debug_enabled }}
    - name: Download thapi build cache
      uses: actions/download-artifact@v4
      with:
        name: thapi_cache_deprecated
        path: ${{ env.DEPRECATED_CACHE_DIR }}
    - name: Checkout dependencies (spack,...)
      uses: ./.github/actions/setup-thapi-deps
      with:
        cache-dir: ${{ env.DEPRECATED_CACHE_DIR }}
    - name: Install ${{ matrix.version }}
      if: ${{ matrix.version != 'thapi@develop ^lttng-tools@master ^lttng-ust@master ^babeltrace2@master' }}
      run: |
        . external/spack/share/spack/setup-env.sh
        spack install $SPACK_OPT ${{ matrix.version }}
    - name: Block to allow inspecting failures
      run: sleep 120m
      if: ${{ failure() && inputs.debug_enabled }}

  install_dependencies:
    runs-on: ubuntu-latest
    name: Install dependencies
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ inputs.debug_enabled }}
    - name: Checkout dependencies (spack,...)
      uses: ./.github/actions/setup-thapi-deps
      with:
        cache-dir: ${{ env.CACHE_DIR }}
    - name: Install llvm/clang version in thapi@develop+clang-parser spec
      shell: bash
      run: |
        # Source spack
        . external/spack/share/spack/setup-env.sh

        # Find the llvm major version in the thapi@develop+clang-parser variant. We
        # need to filter out the fetch lines generated by `spack spec` when it is run
        # for the first time. These lines start with `==>`.
        LLVM_VER=`spack spec -j thapi@develop+clang-parser | grep -v '==>' | jq '.spec.nodes[] | select(.name == "llvm") | .version' | awk '{ split($0,a,"[\".]"); print a[2] }'`

        # Add llvm to apt repository.
        wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
        REPO="deb http://apt.llvm.org/noble/ llvm-toolchain-noble-${LLVM_VER} main"
        echo "$REPO" | sudo tee /etc/apt/sources.list.d/llvm.list
        sudo apt-get update

        # Install llvm/clang
        sudo apt-get install libllvm${LLVM_VER} llvm-${LLVM_VER} llvm-${LLVM_VER}-dev
        sudo apt-get install clang-${LLVM_VER} libclang-${LLVM_VER}-dev python3-clang-${LLVM_VER}

        # Let spack find newly installed llvm/clang.
        spack compiler find
        spack external find --all --exclude bzip2 --exclude xz

        LLVM_FULL_VER=`llvm-config-${LLVM_VER} --version`
        echo "LLVM_FULL_VER=${LLVM_FULL_VER}" >> ${GITHUB_ENV}
    - name: Workaround for providing llvm+python in GitHub CI runners
      shell: bash
      run: |
        # Symlink python3-clang package to site-packages so h2yaml won't fail on
        # `import clang`. This way, our llvm+python trick will work without an issue.
        python_major=$(python -c "import sys; print(f'{sys.version_info.major}')")
        python_minor=$(python -c "import sys; print(f'{sys.version_info.minor}')")
        SITE_PACKAGES=/usr/lib/python${python_major}.${python_minor}/site-packages
        sudo mkdir -p ${SITE_PACKAGES}
        sudo ln -s /usr/lib/python${python_major}/dist-packages/clang ${SITE_PACKAGES}/clang

        # Trick spack to think that llvm found in packages.yml has +python variant:
        sed -i 's/llvm@[0-9][0-9]\.[0-9]\.[0-9]/&+python/' ~/.spack/packages.yaml
    - name: Install dependencies
      run: |
        . external/spack/share/spack/setup-env.sh
        # We have to use the exact llvm version from apt package as a direct dependency
        # as the versions in apt and spack doesn't agree to the patch version. The
        # latter will force spack to build llvm from scratch.
        spack install --only dependencies $SPACK_OPT thapi@develop ^llvm@${LLVM_FULL_VER}
    - name: Upload thapi build cache
      uses: actions/upload-artifact@v4
      with:
        name: thapi_cache
        include-hidden-files: true
        path: ${{ env.CACHE_DIR }}
        if-no-files-found: error
    - name: Block to allow inspecting failures
      run: sleep 120m
      if: ${{ failure() && inputs.debug_enabled }}

  install:
    strategy:
      matrix:
        version: ['thapi@0.0.13', 'thapi@master', 'thapi@develop', 'thapi@develop+archive',
        'thapi@develop ^lttng-tools@master ^lttng-ust@master ^babeltrace2@master']
    needs: install_dependencies
    runs-on: ubuntu-latest
    name: Install ${{ matrix.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ inputs.debug_enabled }}
    - name: Download thapi build cache
      uses: actions/download-artifact@v4
      with:
        name: thapi_cache
        path: ${{ env.CACHE_DIR }}
    - name: Checkout dependencies (spack,...)
      uses: ./.github/actions/setup-thapi-deps
      with:
        cache-dir: ${{ env.CACHE_DIR }}
    - name: Install ${{ matrix.version }}
      if: ${{ matrix.version != 'thapi@develop ^lttng-tools@master ^lttng-ust@master ^babeltrace2@master' }}
      run: |
        . external/spack/share/spack/setup-env.sh
        spack install $SPACK_OPT ${{ matrix.version }} ^llvm@${LLVM_FULL_VER}
    - name: Install thapi@develop with master versions of dependencies
      if: ${{ matrix.version == 'thapi@develop ^lttng-tools@master ^lttng-ust@master ^babeltrace2@master' }}
      continue-on-error: true
      run: |
        . external/spack/share/spack/setup-env.sh
        spack install $SPACK_OPT ${{ matrix.version }} ^llvm@${LLVM_FULL_VER} || true
    - name: Block to allow inspecting failures
      run: sleep 120m
      if: ${{ failure() && inputs.debug_enabled }}

  cleanup:
    needs: [install, install_deprecated]
    if: always()
    runs-on: ubuntu-latest
    name: Cleanup the build cache
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: geekyeggo/delete-artifact@v5
      with:
        name: thapi_cache_deprecated
    - uses: geekyeggo/delete-artifact@v5
      with:
        name: thapi_cache
